export const array = [
   {
      id: 1,
      titulo: 'A verdade da vida',
      volume: 1,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 2,
      titulo: 'A verdade da vida',
      volume: 2,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 3,
      titulo: 'Oração para Cura Divina',
      volume: 0,
      categoria: 'Cura divina',
      autor: '',
      editora: '',
      preco: 5,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto: '',
   },
   {
      id: 4,
      titulo: 'Preceito de mesa tamanho grande',
      volume: 0,
      categoria: 'Preceitos',
      autor: '',
      editora: '',
      preco: 15,
      qtd_venda: 7,
      qtd_estoque: 25,
      foto: '',
   },
   {
      id: 5,
      titulo: 'Sutra sagrada capa azul',
      volume: 0,
      categoria: 'Sutras',
      autor: '',
      editora: 'Seicho No Ie',
      preco: 19,
      qtd_venda: 3,
      qtd_estoque: 50,
      foto: '',
   },
];
