export const array = [
   {
      id: 1,
      titulo: 'A verdade da vida',
      volume: 1,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 2,
      titulo: 'A verdade da vida',
      volume: 2,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 3,
      titulo: 'A verdade da vida',
      volume: 3,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 4,
      titulo: 'A verdade da vida',
      volume: 4,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 5,
      titulo: 'A verdade da vida',
      volume: 5,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 6,
      titulo: 'A verdade da vida',
      volume: 6,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 7,
      titulo: 'A verdade da vida',
      volume: 7,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 8,
      titulo: 'A verdade da vida',
      volume: 8,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 9,
      titulo: 'A verdade da vida',
      volume: 9,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 10,
      titulo: 'A verdade da vida',
      volume: 10,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 11,
      titulo: 'A verdade da vida',
      volume: 11,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 12,
      titulo: 'A verdade da vida',
      volume: 12,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 13,
      titulo: 'A verdade da vida',
      volume: 13,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 14,
      titulo: 'A verdade da vida',
      volume: 14,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 15,
      titulo: 'A verdade da vida',
      volume: 15,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 16,
      titulo: 'A verdade da vida',
      volume: 16,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 17,
      titulo: 'A verdade da vida',
      volume: 17,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 18,
      titulo: 'A verdade da vida',
      volume: 18,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 19,
      titulo: 'A verdade da vida',
      volume: 19,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
];
