export const array = [
   {
      id: 1,
      titulo: 'A verdade da vida',
      volume: 1,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 4,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 2,
      titulo: 'A verdade da vida',
      volume: 2,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 12,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 3,
      titulo: 'A verdade da vida',
      volume: 3,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 5,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 4,
      titulo: 'A verdade da vida',
      volume: 4,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 3,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
   {
      id: 5,
      titulo: 'A verdade da vida',
      volume: 5,
      categoria: 'Livros',
      autor: 'Massaharu Taniguchi',
      editora: 'Seicho No Ie',
      preco: 25.82,
      qtd_venda: 2,
      qtd_estoque: 2,
      foto:
         'https://images-americanas.b2w.io/produtos/01/00/img/27826/4/27826439_1GG.jpg',
   },
];
